version: '3.1'
services:

  redis-server:
      image: redis:latest
      container_name: redis-server
      ports:
        - "6379:6379"
      networks:
        - service_network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - service_network

  postgres:
    image: postgres:17
    container_name: customer_service_postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 2875
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - service_network
    restart: unless-stopped



volumes:
  postgres_data:
networks:
  service_network: