###### Server port ########
server:
  port: 6060  # ${SERVICE_PORT}

spring:
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2875
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        default_schema: customer_service
    show-sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: http://localhost:6060/v3/api-docs

security:
  jwt-expiration-in-ms: 1200000
  jwt-secret: order-management-2024-new-secret-key-project
  jwt-refresh-expiration-in-ms: 1200000

logging:
  level:
    org.springframework.data.redis: DEBUG
    io.lettuce.core: DEBUG