###### Server port ########
server:
  port: 6060  # ${SERVICE_PORT}
  servlet:
    context-path: /customer

spring:
  application:
    name: customer-service
  cloud:
    config:
      enabled: false
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 2875
    hikari:
      maximum-pool-size: 10
      minimum-idle: 5
      idle-timeout: 30000
      connection-timeout: 20000
      max-lifetime: 1800000
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        hbm2ddl:
          auto: none
        default_schema: customer_service
    show-sql: true
  boot:
    admin:
      client:
        url: http://localhost:80
        instance:
          metadata:
            user.name: ${spring.security.user.name}
            user.password: ${spring.security.user.password}
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    url: http://localhost/customer/v3/api-docs

management:
   endpoints:
    web:
      exposure:
        include: "*"
   endpoint:
    health:
      show-details: always

security:
  jwt-expiration-in-ms: 1200000
  jwt-secret: order-management-2024-new-secret-key-project
  jwt-refresh-expiration-in-ms: 1200000
