server:
  port: 80
  servlet:
    context-path: /

spring:
  application:
    name: api-gateway
  main:
    web-application-type: reactive
  security:
    user:
      name: admin
      password: admin
  cloud:
    config:
      enabled: false
    gateway:
      default-filters:
        - PreserveHostHeader=true
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Swagger UI Route
        - id: swagger-ui
          uri: http://localhost:80
          predicates:
            - Path=/swagger-ui/**
          filters:
            - RewritePath=/swagger-ui/(?<segment>.*), /swagger-ui/${segment}
        # API Docs Route for Gateway Aggregation
        - id: api-docs
          uri: http://localhost:80
          predicates:
            - Path=/v3/api-docs/**

        # Customer Service API Docs Route
        - id: customer-service-api-docs
          uri: lb://customer-service
          predicates:
            - Path=/v3/api-docs/customer-service
          filters:
            - RewritePath=/v3/api-docs/customer-service, /v3/api-docs

        # Customer Service Route through Eureka
        - id: customer-service
          uri: lb://customer-service
          predicates:
            - Path=/customer/**
          filters:
            - name: CircuitBreaker
              args:
                name: customer
                fallbackUri: forward:/fallback/fallbackForCustomerService


        # Order Service  API Docs Route
        - id: order-service-api-docs
          uri: lb://order-service
          predicates:
            - Path=/v3/api-docs/order-service
          filters:
            - RewritePath=/v3/api-docs/order-service, /v3/api-docs

        # Order Service Route through Eureka
        - id: order-service
          uri: lb://order-service
          predicates:
            - Path=/order/**
          filters:
            - name: AuthenticationFilter
            - name: CircuitBreaker
              args:
                name: order
                fallbackUri: forward:/fallback/fallbackForOrderService

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs
  swagger-ui:
    enabled: true
    config-url: /v3/api-docs/swagger-config

  management:
    endpoints:
      web:
        exposure:
          include: "*"
    endpoint:
      health:
        show-details: always


eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: localhost
    prefer-ip-address: true


security:
  jwt-secret: be-career-2024-new-secret-key-project
